version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://192.168.15.122:8040
      KC_PROXY: edge
      KC_LOG_LEVEL: debug
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HOSTNAME_ADMIN_URL: http://192.168.15.122:8040
    command: [ "start-dev"]
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    command: ["nginx-debug", '-g', 'daemon off;']
    ports:
      - 8040:80
